sudo: required
services:
  - docker

before_install:
  - docker build -t jji421/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jji421/client-test npm test -- --coverage

after_success:
  - docker build -t jji421/multi-client ./client
  - docker build -t jji421/mutli-nginx ./nginx
  - docker build -t jji421/multi-server ./server
  - docker build -t jji421/mutli-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push jji421/multi-client
  - docker push jji421/mutli-nginx
  - docker push jji421/multi-server
  - docker push jji421/mutli-worker